# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dynamo-eagw.fullname" . }}-epp-config
  labels:
    app.kubernetes.io/name: {{ include "dynamo-eagw.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  epp-config-dynamo.yaml: |
{{ (.Files.Get "epp-config-dynamo.yaml") | indent 4 }}
