name: Lightweight DEP
description: Quick proposal for smaller changes
title: "DEP (light): "
labels: ["dep:draft", "dep:lightweight"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Primary area this DEP affects
      options:
        - external-api
        - frontend
        - router
        - backend-vllm
        - backend-trtllm
        - backend-sglang
        - kv-memory
        - multimodal
        - planner
        - core-platform
        - observability
        - fault-tolerance
        - gateway
        - devops
        - docs
        - process
        - k8s
        - dgdr
        - xpu
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
