# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: tempo
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{service_name=~".+"} | trace_id = "$${__trace.traceId}"'
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
      search:
        hide: false
      nodeGraph:
        enabled: true
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: 1h
        spanEndTimeShift: 1h
      spanBar:
        type: Tag
